### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by GeneralYouri** [GeneralYouri/AOC-Toolkit#2]
### Add useful tools to:
- [ ] Measure code execution time
- [ ] Simplify input parsing
- [ ] Work with grids and other positional systems
- [ ] Use Functional Programming features such as Currying and Function Composition
- [ ] Dynamically import all available solutions to a problem, incase multiple exist

---

### Implement data structures and their operations:
@see https://en.wikipedia.org/wiki/List_of_data_structures
@see https://github.com/trekhleb/javascript-algorithms
- [ ] Enum
- [ ] Collections
- [ ] Queues
- [ ] Lists
- [ ] Linked Lists
- [ ] Trees
- [ ] Graphs
- [ ] Hashes
- [ ] Matrices
- [ ] Grids
